test_list=[(7,8),(5,6),(7,5),(10,4),(10,1)]
print(test_list)
a=list(test_list[0])
b=list(test_list[1])
c=list(test_list[2])
d=list(test_list[3])
e=list(test_list[4])
lista=[]
lista.append(a)
lista.append(b)
lista.append(c)
lista.append(d)
lista.append(e)
print(lista)
print("hola wey")